# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Verify

on:
  pull_request:
    branches: [ 'main', 'release-*' ]
  push:
    branches: [ 'main', 'release-*' ]

jobs:

  verify:
    name: Verify Codegen
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: ./src/github.com/${{ github.repository }}
          fetch-depth: 0

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: './src/github.com/${{ github.repository }}/go.mod'
          check-latest: true

      - run: |
          cd "$(mktemp -d)"
          wget -O protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v27.1/protoc-27.1-linux-x86_64.zip
          unzip protoc.zip -d .
          chmod +x ./bin/protoc
          echo "$(pwd)/bin" >> "$GITHUB_PATH"

      - run: |
          cd $(mktemp -d)
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.33.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

      - working-directory: ./src/github.com/${{ github.repository }}
        run: go generate ./...

      - uses: chainguard-dev/actions/nodiff@main
        with:
          path: ./src/github.com/${{ github.repository }}
          fixup-command: "go generate ./..."